// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: depute.proto

package depute

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Link struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value []byte `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Link) Reset() {
	*x = Link{}
	if protoimpl.UnsafeEnabled {
		mi := &file_depute_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Link) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Link) ProtoMessage() {}

func (x *Link) ProtoReflect() protoreflect.Message {
	mi := &file_depute_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Link.ProtoReflect.Descriptor instead.
func (*Link) Descriptor() ([]byte, []int) {
	return file_depute_proto_rawDescGZIP(), []int{0}
}

func (x *Link) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type Multihash struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value []byte `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Multihash) Reset() {
	*x = Multihash{}
	if protoimpl.UnsafeEnabled {
		mi := &file_depute_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Multihash) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Multihash) ProtoMessage() {}

func (x *Multihash) ProtoReflect() protoreflect.Message {
	mi := &file_depute_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Multihash.ProtoReflect.Descriptor instead.
func (*Multihash) Descriptor() ([]byte, []int) {
	return file_depute_proto_rawDescGZIP(), []int{1}
}

func (x *Multihash) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type Advertisement struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID        *Link  `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Entries   *Link  `protobuf:"bytes,2,opt,name=entries,proto3,oneof" json:"entries,omitempty"`
	ContextId []byte `protobuf:"bytes,3,opt,name=context_id,json=contextId,proto3,oneof" json:"context_id,omitempty"`
	Metadata  []byte `protobuf:"bytes,4,opt,name=metadata,proto3,oneof" json:"metadata,omitempty"`
	Removed   bool   `protobuf:"varint,5,opt,name=removed,proto3" json:"removed,omitempty"`
}

func (x *Advertisement) Reset() {
	*x = Advertisement{}
	if protoimpl.UnsafeEnabled {
		mi := &file_depute_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Advertisement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Advertisement) ProtoMessage() {}

func (x *Advertisement) ProtoReflect() protoreflect.Message {
	mi := &file_depute_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Advertisement.ProtoReflect.Descriptor instead.
func (*Advertisement) Descriptor() ([]byte, []int) {
	return file_depute_proto_rawDescGZIP(), []int{2}
}

func (x *Advertisement) GetID() *Link {
	if x != nil {
		return x.ID
	}
	return nil
}

func (x *Advertisement) GetEntries() *Link {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *Advertisement) GetContextId() []byte {
	if x != nil {
		return x.ContextId
	}
	return nil
}

func (x *Advertisement) GetMetadata() []byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Advertisement) GetRemoved() bool {
	if x != nil {
		return x.Removed
	}
	return false
}

type NotifyContent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NotifyContent) Reset() {
	*x = NotifyContent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_depute_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyContent) ProtoMessage() {}

func (x *NotifyContent) ProtoReflect() protoreflect.Message {
	mi := &file_depute_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyContent.ProtoReflect.Descriptor instead.
func (*NotifyContent) Descriptor() ([]byte, []int) {
	return file_depute_proto_rawDescGZIP(), []int{3}
}

type Publish struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Publish) Reset() {
	*x = Publish{}
	if protoimpl.UnsafeEnabled {
		mi := &file_depute_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Publish) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Publish) ProtoMessage() {}

func (x *Publish) ProtoReflect() protoreflect.Message {
	mi := &file_depute_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Publish.ProtoReflect.Descriptor instead.
func (*Publish) Descriptor() ([]byte, []int) {
	return file_depute_proto_rawDescGZIP(), []int{4}
}

type NotifyContent_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Multihash *Multihash `protobuf:"bytes,1,opt,name=multihash,proto3" json:"multihash,omitempty"`
}

func (x *NotifyContent_Request) Reset() {
	*x = NotifyContent_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_depute_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyContent_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyContent_Request) ProtoMessage() {}

func (x *NotifyContent_Request) ProtoReflect() protoreflect.Message {
	mi := &file_depute_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyContent_Request.ProtoReflect.Descriptor instead.
func (*NotifyContent_Request) Descriptor() ([]byte, []int) {
	return file_depute_proto_rawDescGZIP(), []int{3, 0}
}

func (x *NotifyContent_Request) GetMultihash() *Multihash {
	if x != nil {
		return x.Multihash
	}
	return nil
}

type NotifyContent_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Link *Link `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
}

func (x *NotifyContent_Response) Reset() {
	*x = NotifyContent_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_depute_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyContent_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyContent_Response) ProtoMessage() {}

func (x *NotifyContent_Response) ProtoReflect() protoreflect.Message {
	mi := &file_depute_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyContent_Response.ProtoReflect.Descriptor instead.
func (*NotifyContent_Response) Descriptor() ([]byte, []int) {
	return file_depute_proto_rawDescGZIP(), []int{3, 1}
}

func (x *NotifyContent_Response) GetLink() *Link {
	if x != nil {
		return x.Link
	}
	return nil
}

type Publish_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Advertisement *Advertisement `protobuf:"bytes,1,opt,name=advertisement,proto3" json:"advertisement,omitempty"`
}

func (x *Publish_Request) Reset() {
	*x = Publish_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_depute_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Publish_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Publish_Request) ProtoMessage() {}

func (x *Publish_Request) ProtoReflect() protoreflect.Message {
	mi := &file_depute_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Publish_Request.ProtoReflect.Descriptor instead.
func (*Publish_Request) Descriptor() ([]byte, []int) {
	return file_depute_proto_rawDescGZIP(), []int{4, 0}
}

func (x *Publish_Request) GetAdvertisement() *Advertisement {
	if x != nil {
		return x.Advertisement
	}
	return nil
}

type Publish_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Link *Link `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
}

func (x *Publish_Response) Reset() {
	*x = Publish_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_depute_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Publish_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Publish_Response) ProtoMessage() {}

func (x *Publish_Response) ProtoReflect() protoreflect.Message {
	mi := &file_depute_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Publish_Response.ProtoReflect.Descriptor instead.
func (*Publish_Response) Descriptor() ([]byte, []int) {
	return file_depute_proto_rawDescGZIP(), []int{4, 1}
}

func (x *Publish_Response) GetLink() *Link {
	if x != nil {
		return x.Link
	}
	return nil
}

var File_depute_proto protoreflect.FileDescriptor

var file_depute_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x64, 0x65, 0x70, 0x75, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e,
	0x69, 0x70, 0x6e, 0x69, 0x2e, 0x64, 0x65, 0x70, 0x75, 0x74, 0x65, 0x2e, 0x76, 0x30, 0x22, 0x1c,
	0x0a, 0x04, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x21, 0x0a, 0x09,
	0x4d, 0x75, 0x6c, 0x74, 0x69, 0x68, 0x61, 0x73, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22,
	0xf1, 0x01, 0x0a, 0x0d, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x12, 0x24, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x69, 0x70, 0x6e, 0x69, 0x2e, 0x64, 0x65, 0x70, 0x75, 0x74, 0x65, 0x2e, 0x76, 0x30, 0x2e, 0x4c,
	0x69, 0x6e, 0x6b, 0x52, 0x02, 0x49, 0x44, 0x12, 0x33, 0x0a, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69,
	0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x69, 0x70, 0x6e, 0x69, 0x2e,
	0x64, 0x65, 0x70, 0x75, 0x74, 0x65, 0x2e, 0x76, 0x30, 0x2e, 0x4c, 0x69, 0x6e, 0x6b, 0x48, 0x00,
	0x52, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x88, 0x01, 0x01, 0x12, 0x22, 0x0a, 0x0a,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c,
	0x48, 0x01, 0x52, 0x09, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x49, 0x64, 0x88, 0x01, 0x01,
	0x12, 0x1f, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0c, 0x48, 0x02, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x88, 0x01,
	0x01, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x07, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x64, 0x42, 0x0a, 0x0a, 0x08, 0x5f,
	0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x78, 0x74, 0x5f, 0x69, 0x64, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x6d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x22, 0x89, 0x01, 0x0a, 0x0d, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x43, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x1a, 0x42, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x37, 0x0a, 0x09, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x69, 0x70, 0x6e, 0x69, 0x2e, 0x64, 0x65, 0x70, 0x75, 0x74,
	0x65, 0x2e, 0x76, 0x30, 0x2e, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x68, 0x61, 0x73, 0x68, 0x52, 0x09,
	0x6d, 0x75, 0x6c, 0x74, 0x69, 0x68, 0x61, 0x73, 0x68, 0x1a, 0x34, 0x0a, 0x08, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x69, 0x70, 0x6e, 0x69, 0x2e, 0x64, 0x65, 0x70, 0x75, 0x74,
	0x65, 0x2e, 0x76, 0x30, 0x2e, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x22,
	0x8f, 0x01, 0x0a, 0x07, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x1a, 0x4e, 0x0a, 0x07, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x43, 0x0a, 0x0d, 0x61, 0x64, 0x76, 0x65, 0x72, 0x74,
	0x69, 0x73, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e,
	0x69, 0x70, 0x6e, 0x69, 0x2e, 0x64, 0x65, 0x70, 0x75, 0x74, 0x65, 0x2e, 0x76, 0x30, 0x2e, 0x41,
	0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x0d, 0x61, 0x64,
	0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x1a, 0x34, 0x0a, 0x08, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x69, 0x70, 0x6e, 0x69, 0x2e, 0x64, 0x65, 0x70,
	0x75, 0x74, 0x65, 0x2e, 0x76, 0x30, 0x2e, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x04, 0x6c, 0x69, 0x6e,
	0x6b, 0x32, 0xbb, 0x01, 0x0a, 0x09, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x72, 0x12,
	0x60, 0x0a, 0x0d, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x12, 0x25, 0x2e, 0x69, 0x70, 0x6e, 0x69, 0x2e, 0x64, 0x65, 0x70, 0x75, 0x74, 0x65, 0x2e, 0x76,
	0x30, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x2e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x69, 0x70, 0x6e, 0x69, 0x2e, 0x64,
	0x65, 0x70, 0x75, 0x74, 0x65, 0x2e, 0x76, 0x30, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x43,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28,
	0x01, 0x12, 0x4c, 0x0a, 0x07, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x12, 0x1f, 0x2e, 0x69,
	0x70, 0x6e, 0x69, 0x2e, 0x64, 0x65, 0x70, 0x75, 0x74, 0x65, 0x2e, 0x76, 0x30, 0x2e, 0x50, 0x75,
	0x62, 0x6c, 0x69, 0x73, 0x68, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e,
	0x69, 0x70, 0x6e, 0x69, 0x2e, 0x64, 0x65, 0x70, 0x75, 0x74, 0x65, 0x2e, 0x76, 0x30, 0x2e, 0x50,
	0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x26, 0x5a, 0x24, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x70,
	0x6e, 0x69, 0x2f, 0x64, 0x65, 0x70, 0x75, 0x74, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x30,
	0x3b, 0x64, 0x65, 0x70, 0x75, 0x74, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_depute_proto_rawDescOnce sync.Once
	file_depute_proto_rawDescData = file_depute_proto_rawDesc
)

func file_depute_proto_rawDescGZIP() []byte {
	file_depute_proto_rawDescOnce.Do(func() {
		file_depute_proto_rawDescData = protoimpl.X.CompressGZIP(file_depute_proto_rawDescData)
	})
	return file_depute_proto_rawDescData
}

var file_depute_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_depute_proto_goTypes = []interface{}{
	(*Link)(nil),                   // 0: ipni.depute.v0.Link
	(*Multihash)(nil),              // 1: ipni.depute.v0.Multihash
	(*Advertisement)(nil),          // 2: ipni.depute.v0.Advertisement
	(*NotifyContent)(nil),          // 3: ipni.depute.v0.NotifyContent
	(*Publish)(nil),                // 4: ipni.depute.v0.Publish
	(*NotifyContent_Request)(nil),  // 5: ipni.depute.v0.NotifyContent.Request
	(*NotifyContent_Response)(nil), // 6: ipni.depute.v0.NotifyContent.Response
	(*Publish_Request)(nil),        // 7: ipni.depute.v0.Publish.Request
	(*Publish_Response)(nil),       // 8: ipni.depute.v0.Publish.Response
}
var file_depute_proto_depIdxs = []int32{
	0, // 0: ipni.depute.v0.Advertisement.ID:type_name -> ipni.depute.v0.Link
	0, // 1: ipni.depute.v0.Advertisement.entries:type_name -> ipni.depute.v0.Link
	1, // 2: ipni.depute.v0.NotifyContent.Request.multihash:type_name -> ipni.depute.v0.Multihash
	0, // 3: ipni.depute.v0.NotifyContent.Response.link:type_name -> ipni.depute.v0.Link
	2, // 4: ipni.depute.v0.Publish.Request.advertisement:type_name -> ipni.depute.v0.Advertisement
	0, // 5: ipni.depute.v0.Publish.Response.link:type_name -> ipni.depute.v0.Link
	5, // 6: ipni.depute.v0.Publisher.NotifyContent:input_type -> ipni.depute.v0.NotifyContent.Request
	7, // 7: ipni.depute.v0.Publisher.Publish:input_type -> ipni.depute.v0.Publish.Request
	6, // 8: ipni.depute.v0.Publisher.NotifyContent:output_type -> ipni.depute.v0.NotifyContent.Response
	8, // 9: ipni.depute.v0.Publisher.Publish:output_type -> ipni.depute.v0.Publish.Response
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_depute_proto_init() }
func file_depute_proto_init() {
	if File_depute_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_depute_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Link); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_depute_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Multihash); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_depute_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Advertisement); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_depute_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotifyContent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_depute_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Publish); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_depute_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotifyContent_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_depute_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotifyContent_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_depute_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Publish_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_depute_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Publish_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_depute_proto_msgTypes[2].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_depute_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_depute_proto_goTypes,
		DependencyIndexes: file_depute_proto_depIdxs,
		MessageInfos:      file_depute_proto_msgTypes,
	}.Build()
	File_depute_proto = out.File
	file_depute_proto_rawDesc = nil
	file_depute_proto_goTypes = nil
	file_depute_proto_depIdxs = nil
}
